services:
  - type: web
    name: Chatapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Chatapp.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Chatapp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: Chatapp-db
    plan: free
