services:
  - type: web
    name: Chatapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Chatapp.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
